server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/music_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  redis:
    host: localhost
    port: 6379
    database: 0

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  devtools:
    restart:
      enabled: true  # 启用热部署
      additional-paths: src/main/java  # 监控的目录
      exclude: static/**,public/**  # 排除的目录

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.music.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

jwt:
  secret: your-secret-key
  expiration: 86400000  # 24小时 

file:
  upload:
    path: ./uploads
    max-size: 10485760  # 10MB
    allowed-types: mp3,wav,jpg,png